### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by dmych** [Dyldog/luhman-obsidian-plugin#11] opened 2021-11-08 21:01 UTC
Hello,
I tried to use the plugin but it seems it does not work.
When I execute New Child Zettel Note, or New Sibling Zettel Note, nothing happens. When I execute Open Zettel, it shows no notes at all.
I even tried to create brand new vault, created notes like 1.md, 2.md etc with some content and installed Luhmann plugin only, but it behaves the same way - does nothing.
What should I do to get it working?
Using Obsidian v0.12.19 on Macbook and 1.0.4 on Android.

**Comment by FamRau** [comment] 2021-11-21 12:54
In the settings menu you can find the "id matching rule" option (Strict/ Separator/ Fuzzy). Which option do you use? Because with "Seperator" and "Fuzzy" it works as expected for me. But it seems the "Strict" mode doesn't work at all.

**Comment by dmych** [comment] 2021-11-23 20:23
Already tried all of them with no result.

**Comment by cogscides** [comment] 2021-12-26 13:35
same for me. Not working, but very needed 😥

**Comment by vlthr** [comment] 2022-01-10 10:43
I had the same issues on mobile: the plugin registered commands, but none of them had any effect when called.

After peeking at the source, it looks like the `strict` matching rule (the default setting) doesn’t allow files with `.md` extensions. After changing the matching rule to `fuzzy`, the new sibling/child and go-to-parent commands worked for me.

The open/insert commands still don’t work, and I’m not sure why yet. My best guess is that [getAllTitles](https://github.com/Dyldog/luhman-obsidian-plugin/blob/a7d73bc1268b089c9ebb02f6417c0546310cef35/src/main.ts#L498) is not returning anything. 

I don’t have much experience with the obsidian API — is it possible that the issue is occurring due to [this](https://github.com/Dyldog/luhman-obsidian-plugin/blob/a7d73bc1268b089c9ebb02f6417c0546310cef35/src/main.ts#L488) access to `file.path`, which isn’t part of the [TFile interface](https://github.com/obsidianmd/obsidian-api/blob/c148c24b30dc68d9835820b4169b95d3a038a0f6/obsidian.d.ts#L3123)?

**Comment by Krasser01** [comment] 2022-01-22 15:08
So How to fix it now?

**Comment by brannonh** [comment] 2022-08-30 17:35
Closing this, since #15 was merged. Feel free to reopen, if necessary.

**Closed by brannonh** 2022-08-30 17:35 UTC
