### ISSUE TITLE
Create node commands makes empty links and it doesn't follow me to real Child or Brother/Sister node

### ISSUE THREAD

**Issue by simakovpa** [Dyldog/luhman-obsidian-plugin#17] opened 2022-02-16 17:38 UTC

**Comment by Eforen** [comment] 2022-09-05 17:31
@brannonh why was this closed as far as I can see the issue is not resolved? and there is no comment about it being resolved?

**Comment by brannonh** [comment] 2022-09-06 17:36
> @brannonh why was this closed as far as I can see the issue is not resolved? and there is no comment about it being resolved?

I was just attempting to clean up old items. If this is still an issue, I'm happy to reopen it. I don't fully understand the title, so some elaboration and/or steps to reproduce would be nice.

**Comment by Eforen** [comment] 2022-09-06 23:42
I agree it's confusing but they are I believe talking about the same thing that PR #9 addresses. I would resolve the conflict but I don't know how to without permissions on eather repo...

**Closed** 2022-09-07 04:17 UTC
